language: node_js
node_js:
  - "14"

dist: trusty
sudo: false
addons:
  chrome: stable

cache:
  directories:
    - dist

install:
  - rm -rf node_modules && npm install

jobs:
  allow_failures:
    - name: test app

  include:
    - stage: build
      script:
      - ng lint
      name: check app by linter
    -
      script:
      - ng test --watch=false --browsers ChromeHeadless
      name: test app
    -
      script:
      - ng build --prod --base-href /GreenCityClient/ --aot=false --build-optimizer=false
      name: build app
    - stage: deploy
      script: skip
      name: deploy on gh_pages
      if: branch IN (dev, master)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $TRAVIS_GH_TOKEN
        local_dir: dist/GreenCityClient
        on:
          branch: dev
